# Generated by Django 4.2.6 on 2024-01-03 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_Name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('zone', models.CharField(max_length=20)),
                ('woreda', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('consultant', models.CharField(max_length=20)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('update', models.DateField(auto_now=True)),
                ('catagory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pims.catagory')),
            ],
        ),
    ]
