# Generated by Django 5.0.1 on 2024-03-02 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Catagory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="ProjectInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_Name",
                    models.CharField(max_length=200, verbose_name="Project Name"),
                ),
                ("zone", models.CharField(max_length=20)),
                ("woreda", models.CharField(max_length=20)),
                ("price", models.DecimalField(decimal_places=2, max_digits=100)),
                (
                    "Rebate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=100,
                        verbose_name="Rebate in Percent",
                    ),
                ),
                ("consultant", models.CharField(max_length=20)),
                ("startDate", models.DateField(verbose_name="Start Date")),
                ("endDate", models.DateField(verbose_name=" End Date")),
                ("update", models.DateField(auto_now=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "catagory",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pims.catagory",
                    ),
                ),
            ],
        ),
    ]
