# Generated by Django 5.0.1 on 2024-03-02 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pims", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectinfo",
            old_name="endDate",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="projectinfo",
            old_name="project_Name",
            new_name="project_name",
        ),
        migrations.RenameField(
            model_name="projectinfo",
            old_name="Rebate",
            new_name="rebate",
        ),
        migrations.RenameField(
            model_name="projectinfo",
            old_name="startDate",
            new_name="start_date",
        ),
    ]
