# Generated by Django 5.0.1 on 2024-01-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pims', '0002_alter_catagory_options_alter_projectinfo_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='Rebate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
